version: 2

models:
  - name: stg_customers
    description: Cleaned customer records from Bronze.
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: email

  - name: stg_orders
    description: Cleaned order records from Bronze.
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
